In [4]:
import pandas as pd
import numpy as np

df_test = pd.read_csv("ppr-group-22312913-test.csv")
df_train = pd.read_csv("ppr-group-22312913-train.csv")

print("Shape:", df_train.shape)
display(df_train.head())
display(df_train.info())
print(5 * "******\n")
print("Shape:", df_test.shape)
display(df_test.head())
display(df_test.info())

Shape: (54000, 9)

,Date of Sale (dd/mm/yyyy),Address,County,Eircode,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description
0,01/04/2016,"7 MARLTON DEMESNE, DEMESNE, WICKLOW",Wicklow,NaN,"€450,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
1,15/09/2016,"90 SLIEVE RUA DR, KILMACUD, BLACKROCK",Dublin,NaN,"€560,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
2,21/12/2016,"APT. 1 ABOVE BERGERACS, MAIN STREET, ROASREA",Tipperary,NaN,"€44,200.00",No,No,Second-Hand Dwelling house /Apartment,NaN
3,17/08/2016,"6 MARIEMOUNT GROVE, BALLINAMORE, COUNTY LEITRIM",Leitrim,NaN,"€65,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
4,19/04/2016,"THE GLADE, TYMULLEN, MONASTERBOICE",Louth,NaN,"€400,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN

<class 'pandas.DataFrame'>
RangeIndex: 54000 entries, 0 to 53999
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date of Sale (dd/mm/yyyy)  54000 non-null  str
 1   Address                    54000 non-null  str
 2   County                     54000 non-null  str
 3   Eircode                    16904 non-null  str
 4   Price (€)                  54000 non-null  str
 5   Not Full Market Price      54000 non-null  str
 6   VAT Exclusive              54000 non-null  str
 7   Description of Property    54000 non-null  str
 8   Property Size Description  2775 non-null   str
dtypes: str(9)
memory usage: 3.7 MB

None

******
******
******
******
******

Shape: (10000, 9)

,Date of Sale (dd/mm/yyyy),Address,County,Eircode,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description
0,18/02/2025,"12 ST GABRIELS PLACE, NAAS, KILDARE",Kildare,W91X3HP,"€315,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
1,11/12/2025,"KYLEEN EAST, ELPHIN, ROSCOMMOV",Roscommon,NaN,"€200,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
2,23/09/2025,"9 SUPPLE PARK SHOPPING CENTRE, DUNSHAUGHLIN, C...",Meath,A85AK06,"€180,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN
3,29/05/2025,"1 HAYMARKET, DROGHEDA, LOUTH",Louth,A92X627,"€272,500.00",No,No,Second-Hand Dwelling house /Apartment,NaN
4,25/09/2025,"32 OAKLEY RD, RANELAGH, DUBLIN 6",Dublin,D06N923,"€2,250,000.00",No,No,Second-Hand Dwelling house /Apartment,NaN

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date of Sale (dd/mm/yyyy)  10000 non-null  str
 1   Address                    10000 non-null  str
 2   County                     10000 non-null  str
 3   Eircode                    7401 non-null   str
 4   Price (€)                  10000 non-null  str
 5   Not Full Market Price      10000 non-null  str
 6   VAT Exclusive              10000 non-null  str
 7   Description of Property    10000 non-null  str
 8   Property Size Description  0 non-null      float64
dtypes: float64(1), str(8)
memory usage: 703.3 KB

None

In [8]:
df_train.describe(include="all")

,Date of Sale (dd/mm/yyyy),Address,County,Eircode,Price (€),Not Full Market Price,VAT Exclusive,Description of Property,Property Size Description
count,54000,54000,54000,16904,54000,54000,54000,54000,2775
unique,2479,53315,26,16849,6689,2,2,3,4
top,18/12/2020,"TURLOUGH RD, CASTLEBAR, MAYO",Dublin,P61R261,"€200,000.00",No,No,Second-Hand Dwelling house /Apartment,greater than or equal to 38 sq metres and less...
freq,96,4,16348,2,614,51189,44544,44409,2039